language: node_js
sudo: false
node_js:
  - 6.4

#env:
#  - NODE_ENV=travis"

#matrix:
  #allow_failures:
    #- node_js: 5

services:
  - mongodb

before_install:
  - npm i nsp -g

after_script:
  - nsp audit-package
  - npm run coverage

notifications:
  webhooks:
    urls:
      secure: "L3Lsgk8iH1rXjUsvQy5EvOqOmCcq5PZ/wOxptRczpmz06TMgg0WvK8D+wZYoI1kh+4SUjCaMLK5y1K/j8S/CzxkTN1FvstCVAbSfpnFy/fXLDkC2CWdRCq7Gt64tccloTV0FBlMH3v6qx5vALp3LUSiIxFqdVVGBSrGqeNOx1C/i4r98zJlxh/GsN0NehN2jXV22dJNhVTOuoPDPAbhRXHyOwLGxjL5zHTYGdYIkW/9Te3ouXNr5TX+/v9fcrJulijC04cUNGM5pCQnh0vyLa7I+t+HhAfExwSF7ui45OVU4Egh5wTVTa1R+Pdr5TN21MrQbq6e2bGG5wZyP24S+3nMR5SUibOzgkPLTZbvtiRBdT4KiCsrXZiKh8dFvsUmOdktkxXlfyds3OiR+OQTy6JXBZisUUN8Rsh+nPCxIoSl3GTiU1IxNM4QIgwD7omqUP2hFb+7u4VIftmNWa7VbH+LtRgfFhDfxICGqaZk2akDTeTYWkHdVKSX4JAi1u6ul0dxJw80urm3RPa6oTZQ0/ipE2X4tKg8Yc3lR34GihopY+4KquAiZSBow8u4taVZaIuTW3fKk01KfMU4Jonn1FnW1LwImZiDwnX5eeGNMiqKZ1Jn7bEn6ZbFURCdhqYP+QKmJcVjJswPws/rj5AADsEU9Ms9ky67lvuehFTLQz8M="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
